const EN = {
  "dashboard": "dashboard",
  "classes": "classes",
  "hi": "hi",
  "signupWithGoogle": "Sign up with Google",
  "signupWithFacebook": "Sign up with Facebook",
  "checkBarcode": "Scan the product barcode to see if it's on the",
  "boycott": "Boycott",
  "discoverNow": "Discover Now",
  "searchByProductName": "Search by product name",
  "more": "More...",
  "guidlinesForSearchingByProductName":
      "Search product by writing the name exactly as it appears on the item",
  "productName": "Product Name",
  "indicateYourAnswer": "Please indicate your answer",
  "pleaseEnteraValidStateAbbreviation":
      "Please enter a valid State Abbreviation",
  "emailFormatIsIncorrect": "Email format is incorrect",
  "pleaseProvideYourLastName": "Please provide your Last Name",
  "numbersMustBeInaRangeBetween": "Numbers must be in a range between",
  "numbersMustBeLagrerThan": "Numbers must be larger than",
  "passwordShouldBeAtLeast8Characters":
      "Password should be at least 8 characters",
  "pleaseFillInTheState": "Please fill in the State",
  "pleaseFillInTheEmptyField": "Please fill in the empty field",
  "phoneNumberFormatIsIncorrect": "Phone number format is incorrect",
  "pleaseProvideYourFirstName": "Please provide your First Name",
  "country": "Country",
  "phoneNumber": "Phone Number",
  "title": "Title",
  "answerShouldBeDifferent": "Options should be different",
  "questionsShouldBeDifferent": "Questions should be different",
  "question": "Question",
  "didntFindNamesColumn":
      "Didn't find student name column in the uploaded file",
  "studentNamesDuplicated":
      "There is another student with the same name in the class. Please ensure that names are unique within a single class",
  "studentsRemovedForDuplicationPart1": "Removed",
  "studentsRemovedForDuplicationPart2":
      "students as they were previously added",
  "task": "task",
  "secondShortcut": "sec",
  "minutesShortcut": "min",
  "hoursShortcut": "h",
  "daysShortcut": "day",
  "weeksShortcut": "week",
  "monthsShortcut": "month",
  "yearsShortcut": "year",
  "confirmPassword": "Confirm password",
  "byClickingSignMeUpYouAgreeToTeachyTec":
      "By clicking Sign Me Up, you agree to Teachy Tec Terms of Services and Privacy Policy.",
  "signMeUp": "Sign Me Up",
  "alreadyHaveAnAccount": "Already have an account? Log In",
  "agreeToTermsConditionsAndPrivacyPolicy":
      "I agree to Terms, Conditions and Privacy Policy",
  "continue": "Continue",
  "enterYourEmail": "Enter your email",
  "resetPassword": "Reset Password",
  "checkYourEmail": "Check your email",
  "instructionsToResetYourPasswordHaveBeenSentToYourEmailAddress":
      "Instructions to reset your password have been sent to your email address:",
  "checkMyEmail": "Check My Email",
  "didntRecieveEmailPleaseCheckYourSpamFolder":
      "Didn’t receive the email? Please check your spam folder or",
  "resendResetPasswordEmail": "Resend Reset Password Email",
  "createNewPassword": "Create new password",
  "newPassword": "new password",
  "confirmNewPassword": "confirm new password",
  "save": "Save",
  "delete": "Delete",
  "duplicate": "Duplicate",
  "edit": "Edit",
  "addTask": "Add Task",
  "addStudent": "Add Student",
  "add": "Add",
  "done": "Done",
  "hourShortuct": "hr",
  "secondsShortcut": "sec",
  "home": "Home",
  "transformYourClassroomExperienceOurAppSupportsTeachers":
      "🌐 Transform your classroom experience! Our app supports teachers in evaluating students effortlessly. Upgrade your teaching toolkit now! 🎓",
  "students": "Students",
  "noClassedToDisplay": "No Classes to display yet",
  "className": "Class Name",
  "gradeLevel": "Grade Level",
  "department": "Department",
  "addStudents": "Add Students",
  "uploadExcelSheet": "Upload Excel Sheet",
  "downloadTheFollowingFileToHveCorrectFormat":
      "Download the following file to have the correct format",
  "studentsTemplateFile": "Students Template.xls",
  "gender": "Gender",
  "originalFileAttached": "Original file attached",
  "yourClasses": "Your Classes",
  "classTitle": "Class Title",
  "oldest": "Oldest",
  "newest": "Newest",
  "daily": "Daily",
  "weekly": "Weekly",
  "monthly": "Monthly",
  "addBoard": "Add Board",
  "myGrades": "My Grades",
  "activities": "Activities",
  "chostClassYouWantToGetGrades": "Chose the class you want to get grades",
  "settings": "Setting",
  "language": "Language",
  "privacyPolicyTermsOfUse": "Privacy Policy & Terms of Use",
  "about": "About ",
  "deleteAccount": "Delete Account",
  "arabic": "Arabic",
  "english": "English",
  "permanentDeletionOfYourAccountAndRemovalOfAllPersonalData":
      "Permanent deletion of your account and the removal of all personal data",
  "privacyPolicyDescription":
      "1. Introduction\nWelcome to the privacy policy of CatchyTec (\"we\", \"us\", or \"our\"). This policy is designed to inform you about the types of personal information we collect, how we use and\nprotect that information, and your rights and choices regarding your personal data.\n\n\n2. Information We Collect\n\n2.1 Personal Information\nWe may collect the following types of\npersonal information:\nName\nEmail address\nContact information (e.g., phone number)\nBilling and shipping address\nIP address\nDevice information\nUsage data (e.g., pages visited, interactions)\n\n2.2 Cookies and Tracking Technologies\nWe use cookies and similar technologies to enhance your experience on our website, personalize content, and analyze site traffic. For \ndetailed information on the use of cookies, please refer to our Cookie Policy https://www.teachytec.com.\n\n\n3. How We Use Your Information\nWe use the collected information for the following purposes:\nProviding and improving our services\nProcessing transactions\nCommunicating with you\nAnalyzing website usage and trends\nMarketing and promotional activities (with your consent)\nComplying with legal obligations\n\n\n4. Data Sharing and Third Parties\nWe may share your personal information with third parties under the following circumstances:\nService Providers: We may engage third-party service providers to assist with various aspects of our operations.\nLegal Compliance: We may disclose information when required by law or to protect our rights.\nConsent: With your explicit consent, we may share your information with third parties for specific purposes.\n\n\n5. Your Choices and Rights\n\n5.1 Opt-Out\nYou can opt-out of receiving marketing communications from us by following the unsubscribe instructions in the emails you receive or by contacting us directly.\n\n5.2 Access and Correction\nYou have the right to access and correct your personal information. If you would like to request access or corrections, please contact us at catchytec@gmail.com.\n\n5.3 Data Deletion\nYou can request the deletion of your personal information, subject to legal obligations and legitimate business purposes.\n\n6. Data Security\nWe implement appropriate security measures to protect your personal information from unauthorized access, disclosure, alteration, and destruction.\n\n7. Changes to this Privacy Policy\nWe reserve the right to update this privacy policy to reflect changes in our data practices. Any updates will be effective upon posting the revised policy on our website.\n\n8. Contact Us\nIf you have any questions or concerns about our privacy practices, please contact us at catchytec@gmail.com",
  "wereSorryToSeeYouGo": "We're sorry to see you go!",
  "canYouPleaseTellUsWhyYoureDeletingYourAccount":
      "Can you please tell us why you're deleting your account? Your feedback helps us improve",
  "foundBetterAlternatives": "Found a better alternative",
  "dontWorkHereAnymore": "I don't work here anymore",
  "notSatisfiedWithApp": "Not satisfied with the app",
  "privacyConcerns": "Privacy concerns",
  "other": "Other",
  "pleaseBrieflyExplainReason": "Please briefly explain the reason...",
  "permanetlyDeleteAccount": "Permanently Delete Account",
  "byProceedingYouAreRequestingPermanentDeletionOfYourAccount":
      "By proceeding, you are requesting the permanent deletion of your account and the removal of all associated personal data from the Teachy Tec app.",
  "enterYourRegisteredEmailToConfirmDeletionOfYourAccount":
      "Enter your registered email to confirm the deletion of your account and removal of associated data",
  "yourEmail": "Your email",
  "board": "Board",
  "allStudents": "All students have been chosen. If you'd like to start over",
  "searchByStudentOrClassName": "Search by student or class name",
  "noStudentsToDisplay": "No Students to display",
  "male": "Male",
  "female": "Female",
  "noClassesToDisplay": "No Classes to display",
  "studentsList": "Students List",
  "grade": "Grade",
  "studentDetails": "Student Details",
  "accGrade": "Acc. Grade",
  "yourActivity": "Your Activity",
  "selectMultiDay": "Select multi-day",
  "month": "Month",
  "week": "Week",
  "classActivity": "Class Activity",
  "eraser": "Eraser",
  "addNote": "Add Note",
  "newBoard": "New Activity",
  "editBoard": "Edit Activity",
  "time": "Time",
  "date": "Date",
  "currentDate": "Current Date",
  "back": "back",
  "myActivities": "My Activities",
  "chooseClassForGrading": "Please choose class for grading",
  "view": "View",
  "aboutTeachyTec": "About Teachy Tec",
  "questionMark": "?",
  "areYouSureYouWantToDelete": "Are you sure you want to delete",
  "yourAppDatWillAlsoBeDeletedAndYouWontBeAbleToRetrieve":
      "Your app data will also be deleted and you won't be able to retrieve it.\n\nSince this is a security-sensitive operation, you eventually are asked to login before your account can be deleted.",
  "deletingClassWillPermanentlyEraseAllStudentsData":
      "Deleting the Class will permanently erase all Students data associated with it, and this action cannot be undone.",
  "deletingActivityPageWillResultInIrreversibleLossOfStudentsDegrees":
      "Deleting the activity page will result in irreversible loss of students degrees.",
  "deletingStudentWillResultInIrreversibleLossOfStudentDegrees":
      "Deleting the Student will result in irreversible loss of student degrees.",
  "editClass": "Edit Class",
  "editActivity": "Edit Activity",
  "editStudent": "Edit Student",
  "egTenthGrade": "eg. 10th grade",
  "egMaths": "e.g., Maths",
  "fullName": "Full Name",
  "loading": "Loading",
  "cancel": "cancel",
  "newClass": "New Class",
  "create": "create",
  "class": "Class",
  "yourActivities": "Your Activities",
  "deletingTheClassWillPermanentlyeraseAllStudentDataAssociated":
      "Deleting the Class will permanently erase all Student data associated with it, and this action cannot be undone.",
  "student": "student",
  "pleaseChooseClassForGrading": "Please choose class for grading",
  "currentStudent": "Current Student",
  "classNamesShouldBeUnique":
      "There is a class with the same name, please choose a unique name",
  "activity": "activity",
  "allStudentsHaveBeenSelectedDoYouWantToRestart":
      "All students have been selected, do you want to restart the shuffle for the whole class again?",
  "alreadySelectedStudentsWillBeRemovedWhichMeans":
      "The already selected students will be removed, which means students will be selected again.",
  "confirm": "confirm",
  "am": "am",
  "pm": "pm",
  "setTimer": "Set Timer",
  "taskTitle": "Task title",
  "taskDetails": "task details",
  "loginToTeachyTec": "Log in to Teachy Tec",
  "tapToUploadMedia": "Tap to upload media",
  "tapToUploadPhoto": "Tap to upload photo",
  "mediaConstraints": "(max image size 10 MB, max video size 300 MB)",
  "photoConstraints": "(max image size 10 MB)",
  "photosPermissionDescription":
      "Teachy Tec requires photos permission to Pick media",
  "photosStoragePermissionDescription":
      "Teachy Tec requires photos and storage permissions to Pick media",
  "photosStoragePermission": "Photos and Storage Permissions",
  "photosPermission": "Photos Permission",
  "cameraMicrophonePermissionDescription":
      "Teachy Tec requires permissions for camera and microphone to capture photos and videos",
  "cameraMicrophonePermission": "Camera and Microphone Permission",
  "cameraMicrophonePhotosPermission":
      "Camera, Microphone and Photos Permissions",
  "cameraMicrophonePhotosPermissionDescription":
      "Teachy Tec requires permissions for camera, microphone and photos to access stories",
  "pleaseKeepThisWindowOpen":
      "Please keep this window open while Mr.Tomato is clearing your cache",
  "youChoseUnsupportedElement":
      "You can upload only: \"bmp\", \"jpeg\", \"jpg\", \"pjpeg\", \"png\", \"mov\", \"mp4\", \"quicktime\" formats.",
  "fileSizeWasExceeded": "The file size was exceeded",
  "takePhoto": "Take a Photo",
  "recordVideo": "Record a video",
  "chooseFromGallery": "Choose from gallery",
  "removeCurrentVideo": "Remove current Video",
  "removeCurrentPicture": "Remove current Picture",
  "next": "next",
  "chooseMoreThanNotification_nput_P1": "You can upload",
  "chooseMoreThanNoification_Input_P2": "media items only",
  "choseThisItemBefore": "You chose this item before",
  "activityDeletedSuccessfully": "Activity Deleted scuccessfully",
  "specifyTheQuestion": "Please specify the task",
  "option": "Option",
  "createQuestion": "Create a Question",
  "twoOptionsAtLeastNotification": "Should be two options at least",
  "shouldBeAtleasetOneCorrect": "Should be atleast one option correct",
  "shouldBeAtleastOneIncorrect": "Should be atleast one option incorrect",
  "note": "Note",
  "clearCache": "Clear Cache",
  "clearEntrireCache": "Clear Entire Cache",
  "clearEntireCacheDescription":
      "Teachy Tec uses caching to make the app faster and easier to use. If you have storage or memory issues, you can use \"Clear Entire Cache\" to free up space.\n\nThis will remove stored media and documents, but you can still access them again by re-downloading from the cloud.",
  "cleaningCache": "Cleaning Cache",
  "publishingCahnges": "Publishing Changes",
  "publishChangesMessage":
      "If you press “Publish” all changes will reflect for all locations and users who have access to this item.",
  "publish": "Publish",
  "toCreateBoardYouNeedToHaveAtleastOneClassSoByAccepting":
      "To create a board you need to have at least one class, so by accepting this you will be redirected to the class creation form",
  "score": "SCORE",
  "taskActivity": "Task Activity",
  "wellDone": "Well Done...",
  "couldDoBetter": "Could do better",
  "intelligentBoyWithCoolSenseOfHumour":
      "Intelligent boy with cool sense of humour ❤",
  "youCantEditTasksAsThereAreGradesAssignedToThoseTasks":
      "You can\'t edit tasks as there are grades assigned to those tasks",
  "youCanClearAllGradesByPressingTheButtonBelow":
      "You can clear all the grades by pressing the button below, to enable editing the task",
  "deleteStudentGrades": "Delete student grades",
  "allStudentGradesForThisActivityWilBeDeleted":
      "All Student Grades for this activity will be deleted completely from the system if you proceed",
  "teachyTecAbout":
      "Teachy Tec: Your all-in-one tool for teachers to ace class management, grading, and create fun learning spaces. Streamline learning, guarantee top-notch quality!",
  "signupWithApple": "Sign up with Apple",
  "teachyTecSlogan": "Educate. Excel. Enjoy",
  "teachyTec": "Teachy Tec",
  "textQuestion": "Text Question",
  "multipleOptionsQuestion": "Multiple Options Question",
  "trueFalseQuestion": "True/False Question",
  "true": "true",
  "false": "false",
  "youCanSwipeLeftRight": "You can swipe left/right",
  "yourResponseIsOnPointTrulyMotivational":
      "Your response is on point and truly motivational.",
};
