// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5-Dnod5H4P6pCYzJFl1nrJqvT-E4LsmQ',
    appId: '1:662985789457:web:773e7d5b70139a9fdae1b0',
    messagingSenderId: '662985789457',
    projectId: 'teachytec-dev',
    authDomain: 'teachytec-dev.firebaseapp.com',
    storageBucket: 'teachytec-dev.appspot.com',
    measurementId: 'G-W64WKMRL0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNS130IUULgjnK53YIGeYfvdcOt73vYqs',
    appId: '1:662985789457:android:50f0fa46733b4198dae1b0',
    messagingSenderId: '662985789457',
    projectId: 'teachytec-dev',
    storageBucket: 'teachytec-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgGqG9E8PUvnB8UvXLGyczV1XU3ve5LR8',
    appId: '1:662985789457:ios:523acf40cdd87f66dae1b0',
    messagingSenderId: '662985789457',
    projectId: 'teachytec-dev',
    storageBucket: 'teachytec-dev.appspot.com',
    iosClientId:
        '662985789457-41f5si6mf05ei94jto3pf3bkqctkai60.apps.googleusercontent.com',
    iosBundleId: 'com.catchytec.teachyTec.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgGqG9E8PUvnB8UvXLGyczV1XU3ve5LR8',
    appId: '1:662985789457:ios:b2524f4878d7ee12dae1b0',
    messagingSenderId: '662985789457',
    projectId: 'teachytec-dev',
    storageBucket: 'teachytec-dev.appspot.com',
    iosClientId:
        '662985789457-l1smkc8ntrh9t79fpafvtpm0vluk4ng3.apps.googleusercontent.com',
    iosBundleId: 'com.example.teachyTec.RunnerTests',
  );
}
