// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfHHAbcNDR30jdDgJGTY_d0Npn44Z_MpI',
    appId: '1:189657694988:web:f5210022901db2b922bf29',
    messagingSenderId: '189657694988',
    projectId: 'teachytec',
    authDomain: 'teachytec.firebaseapp.com',
    storageBucket: 'teachytec.appspot.com',
    measurementId: 'G-G0P83B68FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_sDS3Q3QDFAe1Dcf6Wh-vCplaZ0TrwNg',
    appId: '1:189657694988:android:63fc6fa70ab337e822bf29',
    messagingSenderId: '189657694988',
    projectId: 'teachytec',
    storageBucket: 'teachytec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL5bQX6TZIc7CQLBzHiE9diA-lR04P3Nw',
    appId: '1:189657694988:ios:8a427e821b9216b622bf29',
    messagingSenderId: '189657694988',
    projectId: 'teachytec',
    storageBucket: 'teachytec.appspot.com',
    iosBundleId: 'com.example.teachyTec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL5bQX6TZIc7CQLBzHiE9diA-lR04P3Nw',
    appId: '1:189657694988:ios:7e2e2b3637ee016b22bf29',
    messagingSenderId: '189657694988',
    projectId: 'teachytec',
    storageBucket: 'teachytec.appspot.com',
    iosBundleId: 'com.example.teachyTec.RunnerTests',
  );
}
